import { StyleSheet } from 'react-native';
import { headerIconButton } from '../theme/touchTargets';

/** Estilos compartilhados entre Home, lista de veículos e itens do drawer. */
export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgb(215, 239, 253)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
    backgroundColor: 'rgb(215, 239, 253)',
  },
  menuButton: {
    ...headerIconButton,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  locationText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  shareButton: {
    ...headerIconButton,
  },
  headerRightPlaceholder: {
    width: 48,
    height: 48,
  },
  locationToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 8,
    minHeight: 52,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 2,
  },
  locationToggleRowInactive: {
    borderColor: '#F5C4A0',
  },
  locationToggleRowActive: {
    borderColor: '#8FD4A2',
  },
  locationToggleRowPressed: {
    opacity: 0.92,
  },
  locationToggleLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  locationToggleLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  locationToggleLabelInactive: {
    color: '#C97B52',
  },
  locationToggleLabelActive: {
    color: '#2E8B4A',
  },
  scrollView: {
    flex: 1,
  },
  vehicleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(199, 199, 199, 0.38)',
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 24,
    padding: 16,
    borderRadius: 12,
  },
  vehicleText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#0055FF',
    marginLeft: 12,
  },
  plusButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#4A9EFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    paddingBottom: 20,
    justifyContent: 'space-between',
  },
  serviceCard: {
    width: '47%',
    backgroundColor: '#4A9EFF',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    minHeight: 148,
    justifyContent: 'center',
    marginBottom: 14,
  },
  /** Estrela favoritos no card — área de toque ≥ 44pt */
  serviceFavoriteButton: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 9,
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 22,
  },
  /** Chip “Mostrar favoritos” na home */
  filterChipToggle: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F3F3F3',
    paddingVertical: 10,
    paddingHorizontal: 12,
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CCC',
  },
  filterChipToggleText: {
    color: '#333',
    fontSize: 14,
    fontWeight: '500',
  },
  /** Botão fechar modal (cidade) */
  modalCloseButton: {
    ...headerIconButton,
  },
  smallCard: {
    width: '47%',
    minHeight: 96,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  strongBlueCard: {
    backgroundColor: '#0055FF',
  },
  smallCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    flexShrink: 0,
  },
  smallCardTextWrap: {
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'stretch',
    paddingRight: 32,
    minHeight: 36,
  },
  smallCardServiceText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'left',
    lineHeight: 18,
  },
  smallCardServiceSubtext: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.92)',
    textAlign: 'left',
    marginTop: 2,
    lineHeight: 14,
  },
  garagemImage: {
    width: 20,
    height: 20,
  },
  carroImage: {
    width: 70,
    height: 70,
  },
  serviceIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  serviceText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgb(255, 255, 255)',
    textAlign: 'center',
    marginTop: 4,
  },
  serviceSubtext: {
    fontSize: 12,
    color: 'rgb(255, 255, 255)',
    textAlign: 'center',
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    maxHeight: '50%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    minHeight: 52,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalItemText: {
    fontSize: 16,
    color: '#333',
  },
  /** Menu lateral (drawer) — mesma base que a home: rgb(215, 239, 253) + branco + #0055FF */
  sidebarDrawerRoot: {
    flex: 1,
    backgroundColor: 'rgb(215, 239, 253)',
  },
  sidebarScrollContent: {
    flexGrow: 1,
    paddingBottom: 8,
  },
  sidebarHeroGradient: {
    paddingTop: 52,
    paddingBottom: 12,
    paddingHorizontal: 16,
  },
  sidebarProfileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 85, 255, 0.14)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  sidebarUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  sidebarAvatarRing: {
    padding: 3,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: 'rgba(0, 85, 255, 0.22)',
    marginRight: 14,
  },
  sidebarAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  sidebarAvatarImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  sidebarUserDetails: {
    flex: 1,
    minWidth: 0,
  },
  sidebarUserName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#263238',
    marginBottom: 4,
  },
  sidebarUserEmail: {
    fontSize: 12,
    color: '#546E7A',
    lineHeight: 16,
  },
  sidebarProfileHint: {
    marginTop: 12,
    fontSize: 12,
    fontWeight: '600',
    color: '#0055FF',
  },
  sidebarSectionsWrap: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  sidebarSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.9,
    color: '#607D8B',
    marginTop: 18,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  sidebarNavCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 85, 255, 0.12)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  sidebarNavIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 85, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  sidebarNavCardText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#37474F',
    lineHeight: 20,
  },
  sidebarFooter: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(0, 85, 255, 0.18)',
    paddingTop: 14,
    paddingBottom: 4,
    backgroundColor: 'rgb(215, 239, 253)',
  },
  sidebarLogout: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    backgroundColor: '#0055FF',
    marginHorizontal: 16,
    marginBottom: 20,
    borderRadius: 14,
    shadowColor: '#0055FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 5,
  },
  sidebarLogoutText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: 10,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#666',
    marginTop: 20,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999',
    marginTop: 8,
    textAlign: 'center',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0055FF',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 30,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  vehiclesList: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  vehicleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  vehicleItemContent: {
    flex: 1,
  },
  vehicleItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  vehicleItemPlaca: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0055FF',
  },
  vehicleItemTipo: {
    fontSize: 12,
    color: '#666',
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  vehicleItemModelo: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  vehicleItemInsurance: {
    fontSize: 13,
    color: '#555',
  },
  vehicleItemAno: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  vehicleItemBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  vehicleItemBadgeText: {
    fontSize: 12,
    color: '#4CAF50',
    marginLeft: 4,
    fontWeight: '600',
  },
  vehicleItemAction: {
    ...headerIconButton,
    marginLeft: 4,
  },
});
